# Generated by Django 4.2.23 on 2025-06-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
    ]
