# Generated by Django 4.2.23 on 2025-06-19 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_acepta_terminos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pokemones', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='favoritos',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.AddField(
            model_name='equipo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='app.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
